### ISSUE TITLE
Add a question in administrator mode to old diagnostic

### ISSUE THREAD

**Issue by mouchettes** [CASES-LU/diagnostic#16]
Add a question in administrator mode reset all questions ID of the diagnostic to what they were in the administrator mode.
Thereby, if the diagnostic doesn't have these ID, they will be changed, and due to the fact that the question's information are link to the questions ID, they won't be link to the good question anymore.

**Comment by BenjaminJoly** [comment]
The problem mostly happens when try to read older diagnostics, which do not have same ids. Newer diagnostics done in this new version are not affected.

**Comment by BenjaminJoly** [comment]
1.0 files are no more compatible as the calculation method as changed too much. If there is any needs, please feel free to ask.
